// Paths of the self-hosted images generated by scripts/update-assets.mjs (keep `slug` in sync with it).
import type { Champion } from '@/lib/game/types';

const slug = (key: string) => key.toLowerCase().replace(/[^a-z0-9]/g, '');

/** Evolved Kha'Zix variants ("da_18_khazix-executioner") reuse the base champion's image. */
export const championImage = (champion: Champion) => `/assets/champions/${champion.id.split('-')[0]}.webp`;

export const traitIcon = (trait: string) => `/assets/traits/${slug(trait)}.webp`;

export const emblemImage = (trait: string) => `/assets/emblems/${slug(trait)}.webp`;

export const GOLD_ICON = '/assets/ui/gold.webp';
